# Flyway Configuration
flyway.url=jdbc:postgresql://db:5432/koin
flyway.user=koin
flyway.password=123
flyway.schemas=koin
flyway.defaultSchema=koin
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true
flyway.cleanDisabled=true 